name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Vite globally
        run: npm install -g vite

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase Hosting (preview channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIBLOG_LIFEDEV }}
          projectId: miniblog-lifedev
